# Generated by Django 6.0.4 on 2026-04-18 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stage', models.CharField(choices=[('group_stage', 'Group Stage'), ('super16', 'Super 16'), ('super8', 'Super 8'), ('playoffs', 'Playoffs')], max_length=20)),
            ],
            options={
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group_stage', 'Group Stage'), ('super16', 'Super 16'), ('super8', 'Super 8'), ('playoffs', 'Playoffs')], max_length=20)),
                ('match_number', models.IntegerField(default=0)),
                ('team1_total', models.IntegerField(blank=True, null=True)),
                ('team1_overs', models.CharField(blank=True, default='', max_length=10)),
                ('team1_wickets', models.IntegerField(blank=True, null=True)),
                ('team2_total', models.IntegerField(blank=True, null=True)),
                ('team2_overs', models.CharField(blank=True, default='', max_length=10)),
                ('team2_wickets', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.group')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournament.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['stage', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('team', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='groups', through='tournament.GroupMembership', to='tournament.team'),
        ),
        migrations.CreateModel(
            name='PointsTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group_stage', 'Group Stage'), ('super16', 'Super 16'), ('super8', 'Super 8'), ('playoffs', 'Playoffs')], max_length=20)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('tied', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='tournament.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='tournament.team')),
            ],
            options={
                'ordering': ['stage', 'group', 'rank'],
                'unique_together': {('stage', 'team')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'stage')},
        ),
    ]
