# Generated by Django 4.2.30 on 2026-04-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Group A, Group B', max_length=30)),
            ],
            options={
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., World T20 Champions League', max_length=200)),
                ('edition', models.CharField(help_text='e.g., 2026-2027', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Only one tournament should be active at a time. The active tournament is shown on the public site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Group Stage, Super 16, Super 8, Playoffs', max_length=60)),
                ('slug', models.SlugField(help_text='URL slug, e.g., group-stage, super-16, super-8, playoffs', max_length=60)),
                ('stage_type', models.CharField(choices=[('group', 'Group Stage (teams in groups, round-robin)'), ('knockout', 'Knockout / Playoffs (bracket elimination)'), ('round_robin', 'Flat Round Robin (no groups, all vs all)')], default='group', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = earlier in tournament)')),
                ('emoji', models.CharField(blank=True, default='🏏', help_text='Emoji icon for the nav', max_length=10)),
                ('teams_count', models.IntegerField(default=0, help_text='Expected number of teams in this stage')),
                ('groups_count', models.IntegerField(default=0, help_text='Number of groups (0 for flat/knockout stages)')),
                ('qualify_count', models.IntegerField(default=4, help_text='Teams that qualify per group (for points table highlighting)')),
                ('matches_per_pairing', models.IntegerField(default=1, help_text='How many times each team plays against every other team (1=single RR, 2=double RR)')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournament')),
            ],
            options={
                'ordering': ['tournament', 'order'],
                'unique_together': {('tournament', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(default=0)),
                ('team1_total', models.IntegerField(blank=True, help_text='Team 1 total runs', null=True)),
                ('team1_overs', models.CharField(blank=True, default='', help_text='e.g., 20, 19.3', max_length=10)),
                ('team1_wickets', models.IntegerField(blank=True, help_text='Team 1 wickets lost', null=True)),
                ('team2_total', models.IntegerField(blank=True, help_text='Team 2 total runs', null=True)),
                ('team2_overs', models.CharField(blank=True, default='', help_text='e.g., 20, 19.3', max_length=10)),
                ('team2_wickets', models.IntegerField(blank=True, help_text='Team 2 wickets lost', null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('batting_first', models.ForeignKey(blank=True, help_text='Which team batted first. Set automatically if left blank on completed matches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_batted_first', to='tournament.team')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.group')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournamentstage')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournament.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['stage', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('team', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournament.tournamentstage'),
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='stage_groups', through='tournament.GroupMembership', to='tournament.team'),
        ),
        migrations.CreateModel(
            name='PointsTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('tied', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='tournament.group')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='tournament.tournamentstage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='tournament.team')),
            ],
            options={
                'ordering': ['stage', 'group', 'rank'],
                'unique_together': {('stage', 'team')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('stage', 'name')},
        ),
    ]
