# Generated by Django 4.2.30 on 2026-04-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to YouTube match video', max_length=500, null=True),
        ),
    ]
