# Generated by Django 4.2.30 on 2026-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_match_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_overs',
            field=models.IntegerField(default=20, help_text='Maximum overs per innings for this tournament (e.g., 5, 10, 20)'),
        ),
    ]
