# Generated by Django 4.2.30 on 2026-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_max_overs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_wickets',
            field=models.IntegerField(default=10, help_text='Maximum wickets per innings for this tournament (e.g., 10)'),
        ),
    ]
