# Generated by Django 4.2.30 on 2026-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_max_wickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_super_over_runs',
            field=models.IntegerField(blank=True, help_text='Team 1 Super Over runs', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_super_over_wickets',
            field=models.IntegerField(blank=True, help_text='Team 1 Super Over wickets', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_super_over_runs',
            field=models.IntegerField(blank=True, help_text='Team 2 Super Over runs', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_super_over_wickets',
            field=models.IntegerField(blank=True, help_text='Team 2 Super Over wickets', null=True),
        ),
    ]
